table Sales
	lineageTag: 34e211e4-3362-42c6-9b1b-706a3065d82e

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 56328a30-cd39-49df-b7cf-e0bb96a5c987
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 868c4bf0-9ae4-4afc-9698-b89e6b50c67d
			defaultHierarchy: LocalDateTable_7328d559-4538-4e84-be10-fabd7a025f15.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Country
		dataType: string
		lineageTag: 6d341b40-e3bd-4407-bea6-a88411e2ac09
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Product category'
		dataType: string
		lineageTag: aa420e42-64ff-4073-b2f5-371d3ce2fa93
		summarizeBy: none
		sourceColumn: Product category

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 90b630db-1ddd-4892-a3f8-1ac69e65cc90
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column 'Price per item'
		dataType: double
		lineageTag: 6e45cbdd-4ddb-4031-bbb3-c20817633fcb
		summarizeBy: sum
		sourceColumn: Price per item

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sales fact'
		dataType: double
		lineageTag: da5a7adc-ec35-4e57-b20f-d24f12ac0544
		summarizeBy: sum
		sourceColumn: Sales fact

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sales plan'
		dataType: double
		lineageTag: 500b229d-e115-4698-8587-43a011c392da
		summarizeBy: sum
		sourceColumn: Sales plan

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column State
		dataType: string
		lineageTag: 94d149b7-9fab-4e8f-a4d1-d413fca81e1f
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Product subcategory'
		dataType: string
		lineageTag: 1ce9781b-566c-4049-8e6e-bb7edd63717e
		summarizeBy: none
		sourceColumn: Product subcategory

		annotation SummarizationSetBy = Automatic

	column Manager
		dataType: string
		lineageTag: f0f2d829-5c3b-48d8-a2b3-265e86f52c6d
		summarizeBy: none
		sourceColumn: Manager

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("\\Mac\Home\Documents\Excel files\Cycles Sales for the book.xlsx"), null, true),
				    Sales_Sheet = Source{[Item="Sales",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sales_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Country", type text}, {"Product category", type text}, {"Quantity", Int64.Type}, {"Price per item", type number}, {"Sales fact", type number}, {"Sales plan", type number}, {"State", type text}, {"Product subcategory", type text}, {"Manager", type text}, {"Column11", type any}, {"Column12", type any}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column11", "Column12"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

